
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Aug 26 20:29:37 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EQUALITY = 41;
  public static final int LBRACKET = 5;
  public static final int CONST = 16;
  public static final int CHAR = 29;
  public static final int KVADRAT = 55;
  public static final int GREATHERTHAN = 43;
  public static final int QUESTIONMARK = 23;
  public static final int CASE = 38;
  public static final int CONTINUE = 36;
  public static final int LPAREN = 8;
  public static final int SEMI = 7;
  public static final int MINUS = 40;
  public static final int RPAREN = 9;
  public static final int AND = 21;
  public static final int LESSEQUAL = 46;
  public static final int LESSTHAN = 44;
  public static final int OR = 22;
  public static final int COMMA = 13;
  public static final int CLASS = 17;
  public static final int INC = 19;
  public static final int DIV = 48;
  public static final int PLUS = 12;
  public static final int IF = 30;
  public static final int DOT = 25;
  public static final int TARABA = 53;
  public static final int CEZAR = 54;
  public static final int EOF = 0;
  public static final int BOOLEAN = 28;
  public static final int RETURN = 11;
  public static final int RBRACKET = 6;
  public static final int EQUAL = 10;
  public static final int NEW = 24;
  public static final int error = 1;
  public static final int MUL = 47;
  public static final int MOD = 49;
  public static final int NUMBER = 26;
  public static final int ET = 52;
  public static final int BREAK = 35;
  public static final int IDENT = 27;
  public static final int PLUSDVA = 57;
  public static final int VOID = 15;
  public static final int SWITCH = 34;
  public static final int COLON = 39;
  public static final int LBRACE = 3;
  public static final int ELSE = 31;
  public static final int ENUM = 50;
  public static final int READ = 37;
  public static final int GOTO = 59;
  public static final int FINAL = 58;
  public static final int WHILE = 33;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 18;
  public static final int PROG = 2;
  public static final int DEC = 20;
  public static final int MAX = 56;
  public static final int SWAP = 51;
  public static final int NOTEQAUL = 42;
  public static final int PRINT = 14;
  public static final int DO = 32;
  public static final int GREATHEREQUAL = 45;
}

